# Generated by Django 4.2.13 on 2024-06-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('shirt_or_hat', models.CharField(max_length=100)),
                ('quiz_points', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
                ('signup', models.DateField()),
                ('age', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
